NAME = "Azure EventHub"
TYPE = "remote"
FILE = "AzureEventHub.yaml"
VARS = [
    "AZURE_EH_CONNECTIONSTRING",
    "AZURE_EH_CONSUMER_GROUP",
    "AZURE_EH_STORAGE_ACCOUNT",
    "AZURE_EH_STORAGE_ACCOUNT_KEY",
    "AZURE_EH_CONTAINER_NAME",
]
