NAME = "GCP Cloud storage"
TYPE = "remote"
FILE = "GcpStorage.yaml"
VARS = [
    "GCP_STORAGE_BUCKET",
    "GCP_STORAGE_TYPE",
    "GCP_STORAGE_PROJECT_ID",
    "GCP_STORAGE_CLIENT_EMAIL",
    "GCP_STORAGE_PRIVATE_KEY"
]
