FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-build

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install requests

COPY . .
RUN chmod +x run.sh

RUN wget -q https://github.com/dapr/dapr/releases/download/v1.0.1/daprd_linux_amd64.tar.gz
RUN tar -zxvf daprd_linux_amd64.tar.gz

ENV PATH /app:$PATH

CMD ["/bin/bash", "run.sh", "cloudBlock"]
