NAME = "GCP BLOB storage"
TYPE = "output"
FILE = "GcpBlobOutput.yaml"
VARS = [
    "GCP_PUBSUB_BUCKET",
    "GCP_PUBSUB_TYPE",
    "GCP_PUBSUB_PROJECT_ID",
    "GCP_PUBSUB_PRIVATE_KEY_ID",
    "GCP_PUBSUB_CLIENT_EMAIL",
    "GCP_PUBSUB_CLIENT_ID",
    "GCP_PUBSUB_AUTH_URI",
    "GCP_PUBSUB_TOKEN_URI",
    "GCP_PUBSUB_AUTH_PROVIDER_X509_CERT_URL",
    "GCP_PUBSUB_CLIENT_X509_CERT_URL",
    "GCP_PUBSUB_PRIVATE_KEY",
]
