NAME = "GCP Pubsub"
TYPE = "output"
FILE = "GcpPubsubOutput.yaml"
VARS = [
    "GCP_PUBSUB_TOPIC",
    "GCP_PUBSUB_TYPE",
    "GCP_PUBSUB_PROJECT_ID",
    "GCP_PUBSUB_CLIENT_EMAIL",
    "GCP_PUBSUB_PRIVATE_KEY"
]
