NAME = "GCP Secrets"
TYPE = "secrets"
FILE = "GcpSecretManager.yaml"
VARS = [
    "GCP_SECRETMGR_TYPE",
    "GCP_SECRETMGR_PROJECT_ID",
    "GCP_SECRETMGR_CLIENT_EMAIL",
    "GCP_SECRETMGR_PRIVATE_KEY"
]
