NAME = "GCP Secrets"
TYPE = "secrets"
FILE = "GcpSecretManager.yaml"
VARS = [
    "GCP_SECRETMGR_TYPE",
    "GCP_SECRETMGR_PROJECT_ID",
    "GCP_SECRETMGR_PRIVATE_KEY_ID",
    "GCP_SECRETMGR_CLIENT_EMAIL",
    "GCP_SECRETMGR_CLIENT_ID",
    "GCP_SECRETMGR_AUTH_URI",
    "GCP_SECRETMGR_TOKEN_URI",
    "GCP_SECRETMGR_AUTH_PROVIDER_X509_CERT_URL",
    "GCP_SECRETMGR_CLIENT_X509_CERT_URL",
    "GCP_SECRETMGR_PRIVATE_KEY",
]
