FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.8-stretch-build

WORKDIR /app

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip 
RUN pip3 install --user -r /requirements.txt

COPY . .
RUN mkdir -p /app/components/secrets

RUN ./download.sh "%%BALENA_ARCH%%"

ENV PATH /app:$PATH

CMD ["/bin/bash", "run.sh", "cloudBlock"]

