FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.8-stretch-build

WORKDIR /app

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip 
RUN pip3 install --user -r /requirements.txt

COPY . .
RUN mkdir -p /app/components

RUN wget -q https://github.com/dapr/dapr/releases/download/v1.0.1/daprd_linux_amd64.tar.gz
RUN tar -zxvf daprd_linux_amd64.tar.gz

ENV PATH /app:$PATH

CMD ["/bin/bash", "run.sh", "cloudBlock"]

